// <auto-generated />
using System;
using ExamAutomation.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamAutomation.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211111120210_first_again_3")]
    partial class first_again_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ExamAutomation.Domain.Models.ExamQuestionsMapping", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestionsMapping");
                });

            modelBuilder.Entity("ExamAutomation.Domain.Models.Exams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamAutomation.Domain.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnsA")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsB")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsC")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExamsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamsId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamAutomation.Domain.Models.ExamQuestionsMapping", b =>
                {
                    b.HasOne("ExamAutomation.Domain.Models.Exams", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAutomation.Domain.Models.Questions", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamAutomation.Domain.Models.Questions", b =>
                {
                    b.HasOne("ExamAutomation.Domain.Models.Exams", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamsId");
                });

            modelBuilder.Entity("ExamAutomation.Domain.Models.Exams", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
